# Single source of truth for all enum values across agents and supervisor.
# To add/remove a valid value, change it here — all modules auto-update.

VALID_SETUPS = [
    "Bull Flag",
    "Bear Flag",
    "Breakout",
    "Breakdown",
    "Reversal",
    "Inside Bar",
    "EMA Bounce",
    "Support Bounce",
    "Resistance Rejection",
    "Opening Range Breakout",
    "Gap Fill",
    "VWAP Reclaim",
    "VWAP Rejection",
    "Trend Continuation",
    "Double Bottom",
    "Double Top",
    "Head and Shoulders",
    "Inverse Head and Shoulders",
    "Cup and Handle",
    "Wedge Breakout",
    "Wedge Breakdown",
    "Channel Breakout",
    "Momentum",
    "Pullback",
    "Scalp",
    "Other",
]

VALID_EMOTIONS = [
    "Confident",
    "Neutral",
    "Anxious",
    "Fearful",
    "Greedy",
    "Revenge",
    "FOMO",
    "Disciplined",
    "Tired",
    "Excited",
    "Calm",
    "Frustrated",
    "Impatient",
    "Overconfident",
    "Patient",
]

VALID_MARKETS = [
    "Trending",
    "Ranging",
    "Volatile",
    "Choppy",
    "Breakout",
    "Low Volume",
    "High Volume",
    "Pre-Market",
    "Post-Market",
    "News-Driven",
    "Normal",
    "Bull",
    "Bear",
    "Sideways",
]

# Map common variants/typos to valid values
SETUP_ALIASES = {
    "bullflag": "Bull Flag",
    "bull_flag": "Bull Flag",
    "bearflag": "Bear Flag",
    "bear_flag": "Bear Flag",
    "bo": "Breakout",
    "bd": "Breakdown",
    "rev": "Reversal",
    "ib": "Inside Bar",
    "ema": "EMA Bounce",
    "orb": "Opening Range Breakout",
    "gap": "Gap Fill",
    "vwap": "VWAP Reclaim",
    "trend": "Trend Continuation",
    "dbl_bot": "Double Bottom",
    "dbl_top": "Double Top",
    "h&s": "Head and Shoulders",
    "ihs": "Inverse Head and Shoulders",
    "c&h": "Cup and Handle",
    "wedge_up": "Wedge Breakout",
    "wedge_dn": "Wedge Breakdown",
    "pull": "Pullback",
    "momentum": "Momentum",
}

EMOTION_ALIASES = {
    "neutral": "Neutral",
    "calm": "Calm",
    "fear": "Fearful",
    "scared": "Fearful",
    "greed": "Greedy",
    "revenge_trade": "Revenge",
    "fomo": "FOMO",
    "disciplined": "Disciplined",
    "overconfident": "Overconfident",
    "confident": "Confident",
    "anxious": "Anxious",
    "tired": "Tired",
    "excited": "Excited",
    "frustrated": "Frustrated",
    "impatient": "Impatient",
    "patient": "Patient",
}

MARKET_ALIASES = {
    "trend": "Trending",
    "trending": "Trending",
    "range": "Ranging",
    "ranging": "Ranging",
    "chop": "Choppy",
    "choppy": "Choppy",
    "volatile": "Volatile",
    "vol": "Volatile",
    "low_vol": "Low Volume",
    "high_vol": "High Volume",
    "pre": "Pre-Market",
    "post": "Post-Market",
    "news": "News-Driven",
    "normal": "Normal",
    "bull": "Bull",
    "bear": "Bear",
    "sideways": "Sideways",
    "flat": "Sideways",
    "breakout": "Breakout",
}
